# .gitlab-ci.yml

stages:
  - test
  - build-image
  - deploy

Running Test:
  stage: test
  script:
    - echo "Running test"

Docker Image Build:
  stage: build-image
  image:
    name: docker/compose:1.23.2
    entrypoint: ["/bin/sh", "-c"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

  services:
    - docker:dind

  before_script:
    - docker version
    - docker-compose version

  script:
    - docker-compose build
    - docker login -u=$CI_REGISTRY_USER -p=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push itechub/jane-mysql:latest
    - docker push itechub/jane-nginx:latest
    - docker push itechub/jane-django:latest

    # push for tags
    - "[[ -z $CI_BUILD_TAG ]] && exit 0"
    - docker tag $itechub/jane-nginx:latest itechub/jane-nginx:$CI_BUILD_TAG
    - docker tag $itechub/jane-django:latest itechub/jane-django:$CI_BUILD_TAG
    - docker push itechub/jane-nginx:$CI_BUILD_TAG
    - docker push itechub/jane-django:$CI_BUILD_TAG
  only:
    - develop
  tags:
    - docker

Staging:
  stage: staging
  script:
    - mkdir -p /home/gitlab-runner/develop && rsync -r $CI_PROJECT_DIR /home/gitlab-runner/develop
    - cd /home/gitlab-runner/develop/jane && docker-compose build && docker-compose down && docker-compose up -d
  tags:
    - web-client
  only:
    - develop

Production:
  stage: production
  script:
    - mkdir -p /home/gitlab-runner/production && rsync -r $CI_PROJECT_DIR /home/gitlab-runner/production
    - cd /home/gitlab-runner/production/jane && docker-compose build && docker-compose down && docker-compose up -d
  tags:
    - web-client
  only:
    - master
# vim:ft=ansible
